# Configs for pwills.com

title: "Home page"
name: "huukim"
email: huukim136@gmail.com
url: "https://avocado136.github.io/"
repository: "avocado136/avocado136.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
# theme: minimal-mistakes-jekyll
theme: jekyll-theme-time-machine
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
  
# settings for author profile
author:
  name   : "Huu Kim Nguyen"
  avatar : "/assets/images/avatar2.png"
  bio    : "Speech and Audio Signal Processing, Speech Synthesis, Deep Learning and Life Adventure."
  location: "Seoul, South Korea"
  github : huukim136
  linkedin: kim-nguyen136
  email  : huukim136@gmail.com


# # comments by disqus
comments:
  layout: default
  comments: true
  provider: "disqus"
  disqus:
    shortname: "avocado136.github.io"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true

github: [metadata]
